# bindings property file
spring:
  cloud:
    function:
      definition: projectConsumer
    stream:
      kafka:
        bindings:
          projectConsumer-in-0:
            consumer:
              autoCommitOffset: true
      bindings:
        projectConsumer-in-0:
          destination: ${PROJECT_TOPIC:project-info}
          group: "prf"