# bindings property file
spring:
  cloud:
    function:
      definition: projectConsumer
    stream:
      bindings:
        projectConsumer-in-0:
          destination: ${PROJECT_TOPIC:project-info}
          group: "prf"